version = 0.1
[default.deploy.parameters]
stack_name = "product-service"
resolve_s3 = true
s3_prefix = "product-service"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
